# Generated by Django 2.2.6 on 2020-05-03 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(default='Unknown', max_length=20)),
                ('keyword_id', models.PositiveIntegerField(default=0)),
                ('formal_name', models.CharField(max_length=100)),
                ('alias_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='explain',
            fields=[
                ('explain_id', models.PositiveIntegerField(default=0, primary_key=True, serialize=False)),
                ('explain_name', models.CharField(max_length=100)),
                ('timeliness', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=20)),
                ('efficacyLevel', models.CharField(max_length=20)),
                ('releaseDate', models.BigIntegerField()),
                ('effectiveDate', models.BigIntegerField()),
                ('legalCategories', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('total', models.PositiveIntegerField(default=0)),
                ('origin_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='judge_clause_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weibo_id', models.BigIntegerField(default=0)),
                ('belong_to_law', models.CharField(max_length=70)),
                ('belong_to_clause', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='judge_law_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weibo_id', models.BigIntegerField(default=0)),
                ('belong_to_law', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='law',
            fields=[
                ('law_id', models.PositiveIntegerField(default=0, primary_key=True, serialize=False)),
                ('law_name', models.CharField(max_length=100)),
                ('timeliness', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=20)),
                ('efficacyLevel', models.CharField(max_length=20)),
                ('releaseDate', models.BigIntegerField()),
                ('effectiveDate', models.BigIntegerField()),
                ('legalCategories', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('total', models.PositiveIntegerField(default=0)),
                ('origin_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='multi_version_law',
            fields=[
                ('law_id', models.PositiveIntegerField(default=0, primary_key=True, serialize=False)),
                ('law_name', models.CharField(max_length=100)),
                ('ful_name', models.CharField(max_length=100)),
                ('timeliness', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=20)),
                ('efficacyLevel', models.CharField(max_length=20)),
                ('releaseDate', models.BigIntegerField()),
                ('effectiveDate', models.BigIntegerField()),
                ('legalCategories', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('total', models.PositiveIntegerField(default=0)),
                ('origin_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='nn_auto_label_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weibo_id', models.BigIntegerField(default=0)),
                ('belong_to_law', models.CharField(max_length=70)),
                ('belong_to_clause', models.CharField(max_length=30)),
                ('law_id', models.PositiveIntegerField(default=0)),
                ('clause_id', models.PositiveIntegerField(default=0)),
                ('content', models.TextField(default='nothing')),
                ('weibo_content', models.TextField(default='nothing')),
                ('label', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='nn_fine_grain_training_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weibo_id', models.BigIntegerField(default=0)),
                ('belong_to_law', models.CharField(max_length=70)),
                ('belong_to_clause', models.CharField(max_length=30)),
                ('law_id', models.PositiveIntegerField(default=0)),
                ('clause_id', models.PositiveIntegerField(default=0)),
                ('content', models.TextField(default='nothing')),
                ('weibo_content', models.TextField(default='nothing')),
                ('label', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='nn_label_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weibo_id', models.BigIntegerField(default=0)),
                ('belong_to_law', models.CharField(max_length=70)),
                ('belong_to_clause', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='nn_random_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weibo_link', models.URLField(default='#')),
                ('weibo_id', models.BigIntegerField(default=0)),
                ('tou_xiang', models.URLField()),
                ('author_name', models.CharField(max_length=30)),
                ('doc_text', models.TextField()),
                ('weibo_source', models.TextField()),
                ('doc_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='random_selected_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weibo_link', models.URLField(default='#')),
                ('weibo_id', models.BigIntegerField(default=0)),
                ('tou_xiang', models.URLField()),
                ('author_name', models.CharField(max_length=30)),
                ('doc_text', models.TextField()),
                ('weibo_source', models.TextField()),
                ('doc_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='real_clause_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weibo_id', models.BigIntegerField(default=0)),
                ('belong_to_law', models.CharField(max_length=70)),
                ('belong_to_clause', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='real_law_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weibo_id', models.BigIntegerField(default=0)),
                ('belong_to_law', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='solr_weibo_data',
            fields=[
                ('weibo_id', models.BigIntegerField(default=0, primary_key=True, serialize=False)),
                ('law_process', models.IntegerField(default=0)),
                ('clause_process', models.IntegerField(default=0)),
                ('weibo_link', models.URLField(default='https://baidu.com')),
                ('user_type', models.CharField(default='unknown', max_length=20)),
                ('author_name', models.CharField(default='unknown', max_length=30)),
                ('tou_xiang', models.URLField(default='https://baidu.com')),
                ('doc_time', models.BigIntegerField(default=0)),
                ('doc_date', models.DateField(default='2019-01-01')),
                ('doc_text', models.TextField(default='nothing')),
                ('weibo_source', models.TextField(default='nothing')),
                ('opinion', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='stopword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='timestamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(default=2019)),
                ('month', models.PositiveIntegerField(default=1)),
                ('day', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='multi_version_law_clause',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('law_id', models.PositiveIntegerField(default=0)),
                ('clause_id', models.PositiveIntegerField(default=0)),
                ('ful_name', models.CharField(max_length=100)),
                ('law_name', models.CharField(max_length=100)),
                ('clause_name', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('total', models.PositiveIntegerField(default=0)),
                ('origin_count', models.PositiveIntegerField(default=0)),
                ('feature_words', models.TextField(default='/')),
                ('spacial_words', models.TextField(default='/a=0.1/')),
            ],
            options={
                'unique_together': {('law_id', 'clause_id')},
            },
        ),
        migrations.CreateModel(
            name='matched_law_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weibo_id', models.BigIntegerField(default=0)),
                ('keyword_id', models.PositiveIntegerField(default=0)),
                ('keyword_name', models.CharField(default='Unknown', max_length=100)),
                ('weibo_link', models.URLField(default='https://baidu.com')),
                ('data_type', models.CharField(default='Unknown', max_length=20)),
                ('user_type', models.CharField(default='Unknown', max_length=20)),
                ('author_name', models.CharField(default='Unknown', max_length=30)),
                ('tou_xiang', models.URLField(default='https://baidu.com')),
                ('doc_time', models.BigIntegerField(default=0)),
                ('doc_date', models.DateField(default='2019-01-01')),
                ('doc_text', models.TextField(default='None')),
                ('weibo_source', models.TextField(default='None')),
                ('opinion', models.IntegerField(default=0)),
                ('origin_tag', models.IntegerField(default=0)),
                ('source_tag', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': {('weibo_id', 'keyword_id', 'data_type')},
            },
        ),
        migrations.CreateModel(
            name='matched_clause_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weibo_id', models.BigIntegerField(default=0)),
                ('keyword_id', models.PositiveIntegerField(default=0)),
                ('element_id', models.PositiveIntegerField(default=0)),
                ('keyword_name', models.CharField(default='Unknown', max_length=100)),
                ('element_name', models.CharField(default='Unknown', max_length=20)),
                ('weibo_link', models.URLField(default='https://baidu.com')),
                ('data_type', models.CharField(default='Unknown', max_length=20)),
                ('user_type', models.CharField(default='Unknown', max_length=20)),
                ('author_name', models.CharField(default='Unknown', max_length=30)),
                ('tou_xiang', models.URLField(default='https://baidu.com')),
                ('doc_time', models.BigIntegerField(default=0)),
                ('doc_date', models.DateField(default='2019-01-01')),
                ('doc_text', models.TextField(default='None')),
                ('weibo_source', models.TextField(default='None')),
                ('opinion', models.IntegerField(default=0)),
                ('origin_tag', models.IntegerField(default=0)),
                ('source_tag', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': {('weibo_id', 'keyword_id', 'element_id', 'data_type')},
            },
        ),
        migrations.CreateModel(
            name='law_clause',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('law_id', models.PositiveIntegerField(default=0)),
                ('clause_id', models.PositiveIntegerField(default=0)),
                ('law_name', models.CharField(max_length=100)),
                ('clause_name', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('total', models.PositiveIntegerField(default=0)),
                ('origin_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'unique_together': {('law_id', 'clause_id')},
            },
        ),
        migrations.CreateModel(
            name='law_charts_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('law_id', models.PositiveIntegerField(default=0)),
                ('law_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('total', models.PositiveIntegerField(default=0)),
                ('origin_count', models.PositiveIntegerField(default=0)),
                ('rate', models.FloatField(default=1.0)),
            ],
            options={
                'unique_together': {('law_id', 'date')},
            },
        ),
        migrations.CreateModel(
            name='explain_element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explain_id', models.PositiveIntegerField(default=0)),
                ('element_id', models.PositiveIntegerField(default=0)),
                ('explain_name', models.CharField(max_length=100)),
                ('element_name', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('total', models.PositiveIntegerField(default=0)),
                ('origin_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'unique_together': {('explain_id', 'element_id')},
            },
        ),
        migrations.CreateModel(
            name='explain_charts_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explain_id', models.PositiveIntegerField(default=0)),
                ('explain_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('total', models.PositiveIntegerField(default=0)),
                ('origin_count', models.PositiveIntegerField(default=0)),
                ('rate', models.FloatField(default=1.0)),
            ],
            options={
                'unique_together': {('explain_id', 'date')},
            },
        ),
    ]
